### ISSUE TITLE
`.explain()` on tree-based models throws SQL `SyntaxError`

### ISSUE THREAD

**Issue by bryanculver** [matthiask/django-tree-queries#46]
**Steps to Reproduce:**
- Create a `TreeNode` model (example below uses `Location` for model name)
- Perform migrations
- Try to run `Model.objects.all().explain()`

**Expected Outcome:**
SQL explain output:

```
>>> Device.objects.all().explain()
'Sort  (cost=11.91..12.04 rows=50 width=1508)\n  Sort Key: _name\n  ->  Seq Scan on dcim_device  (cost=0.00..10.50 rows=50 width=1508)'
```

**Actual Outcome:**
`psycopg2.errors.SyntaxError: syntax error at or near "EXPLAIN"` / `django.db.utils.ProgrammingError: syntax error at or near "EXPLAIN"` error thrown:

```
>>> Location.objects.all().explain()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
psycopg2.errors.SyntaxError: syntax error at or near "EXPLAIN"
LINE 26:     EXPLAIN SELECT (__tree.tree_depth) AS "tree_depth", (__t...
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 817, in explain
    return self.query.explain(using=self.db, format=format, **options)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 575, in explain
    return '\n'.join(compiler.explain_query())
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1228, in explain_query
    result = list(self.execute_sql())
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.ProgrammingError: syntax error at or near "EXPLAIN"
LINE 26:     EXPLAIN SELECT (__tree.tree_depth) AS "tree_depth", (__t...
```

**Comment by matthiask** [comment]
Thanks for the report. I'm not 100% sure but I have a suspicion. The CTE compiler prepends the CTE statement in `as_sql`, here https://github.com/matthiask/django-tree-queries/blob/f79c508f26556b59f2e144f78020aa332bd2a288/tree_queries/compiler.py#L276 – but `EXPLAIN` should be moved to the beginning of the whole query instead.

You could check what happens if you do something like:

If `sql[0]` begins with `EXPLAIN`, strip it and insert it before the `CTE.format(**params)` statement instead.

This may just be sufficient to get it working and if it does, I think this change would be potentially stable enough to ship it in a release of django-tree-queries.

**Comment by bryanculver** [comment]
> Thanks for the report. I'm not 100% sure what's going on but I have a suspicion. The CTE compiler prepends the CTE statement in `as_sql`, here
> 
> https://github.com/matthiask/django-tree-queries/blob/f79c508f26556b59f2e144f78020aa332bd2a288/tree_queries/compiler.py#L276
> 
> – but `EXPLAIN` should be moved to the beginning of the whole query instead.
> You could check what happens if you do something like:
> 
> If `sql[0]` begins with `EXPLAIN`, strip it and insert it before the `CTE.format(**params)` statement instead.
> 
> This may just be sufficient to get it working and if it does, I think this change would be potentially stable enough to ship it in a release of django-tree-queries.

Hacky but it works!

```py
#...
        sql_explain = ""
        sql_0 = sql[0]
        if sql_0.startswith("EXPLAIN"):
            sql_0 = sql_0.split(' ', 1)[1]
            sql_explain = "EXPLAIN"
        return ("".join([sql_explain, CTE.format(**params), sql_0]), sql[1])
#...
```

```
>>> Location.objects.all().explain()
'Sort  (cost=138.85..139.00 rows=60 width=1280)\n  Sort Key: __tree.tree_ordering\n  CTE __tree\n    ->  Recursive Union  (cost=0.14..123.43 rows=101 width=84)\n          ->  Index Scan using dcim_location_parent_id_d77f3318 on dcim_location t  (cost=0.14..8.16 rows=1 width=84)\n                Index Cond: (parent_id IS NULL)\n          ->  Hash Join  (cost=0.33..11.32 rows=10 width=84)\n                Hash Cond: (t_1.parent_id = __tree_1.tree_pk)\n                ->  Seq Scan on dcim_location t_1  (cost=0.00..10.60 rows=60 width=250)\n                ->  Hash  (cost=0.20..0.20 rows=10 width=84)\n                      ->  WorkTable Scan on __tree __tree_1  (cost=0.00..0.20 rows=10 width=84)\n  ->  Hash Join  (cost=11.35..13.65 rows=60 width=1280)\n        Hash Cond: (__tree.tree_pk = dcim_location.id)\n        ->  CTE Scan on __tree  (cost=0.00..2.02 rows=101 width=84)\n        ->  Hash  (cost=10.60..10.60 rows=60 width=1212)\n              ->  Seq Scan on dcim_location  (cost=0.00..10.60 rows=60 width=1212)'
```
